# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - webappraju

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test
          run: dotnet test --no-build --verbosity normal
        - name: Publish
          run: dotnet publish DotNetSampleRepo/DotNet6WithGithubActions.csproj -c Release -o release --nologo
        - name: Upload Build Artifact
          uses: actions/upload-artifact@v2
          with:
            name: Application_Artifact
            path: /home/runner/work/DotNetSampleRepo/DotNetSampleRepo/release/

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: https://webappraju.azurewebsites.net/ #${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: Application_Artifact

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'webappraju'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1234 }}
          package: .
